name = "a069-webhook"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production.vars]
SLACK_CHANNEL = "C04SDEC0UHZ"
SLACK_NOTIFICATIONS_ENABLED = "true"
ADMIN_KEY = "your-secure-admin-key-here"

[env.development.vars]
SLACK_CHANNEL = "C04SDEC0UHZ"
SLACK_NOTIFICATIONS_ENABLED = "true"
ADMIN_KEY = "dev-admin-key"

# Bot token will be added as a secret via: wrangler secret put SLACK_BOT_TOKEN