name = "a069-webhook"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production.vars]
SLACK_CHANNEL = "C04SDEC0UHZ"
SLACK_NOTIFICATIONS_ENABLED = "true"

[env.development.vars]
SLACK_CHANNEL = "C04SDEC0UHZ"
SLACK_NOTIFICATIONS_ENABLED = "true"

# Bot token will be added as a secret via: wrangler secret put SLACK_BOT_TOKEN